In [2]:
file_names = ['Jane_Austen.txt' , 'Franz_Kafka.txt' , 'Charles_Dickens.txt' , 'Emily_Bronte.txt']
file_name = ["Three plays for Puritans, The devil's disciple, Cæsar and Cleopatra, & Captain Brassbound's conversion_djvu.txt",
"Widowers' housesa play_djvu.txt","Arms and the man; an anti-romantic comedy in three acts_djvu.txt",
"Back to Methuselah. A metabiological pentateuch_djvu.txt",
"Bernard Shaw on modern typography_djvu.txt",
"Candida a pleasant play_djvu.txt",
"Charles_Dickens.txt",
"Dramatic opinions and essays_djvu.txt",
"D:\RUSHIL - 2021-24\Programming 2022-23\ML-and-AI-Practice\Project WiLLM\Emily_Bronte.txt",
"D:\RUSHIL - 2021-24\Programming 2022-23\ML-and-AI-Practice\Project WiLLM\Fabianism and the empire ,a manifesto by the Fabian society_djvu.txt",
"D:\RUSHIL - 2021-24\Programming 2022-23\ML-and-AI-Practice\Project WiLLM\Franz_Kafka.txt",
"D:\RUSHIL - 2021-24\Programming 2022-23\ML-and-AI-Practice\Project WiLLM\Jane_Austen.txt",
"D:\RUSHIL - 2021-24\Programming 2022-23\ML-and-AI-Practice\Project WiLLM\Man and superman; a comedy and a philosophy_djvu.txt",
"D:\RUSHIL - 2021-24\Programming 2022-23\ML-and-AI-Practice\Project WiLLM\Misalliance, The dark lady of the Sonnets, and Fanny's first play_djvu.txt",
"D:\RUSHIL - 2021-24\Programming 2022-23\ML-and-AI-Practice\Project WiLLM\Mrs. Warren's profession ; a play in four act_djvu.txt",
"D:\RUSHIL - 2021-24\Programming 2022-23\ML-and-AI-Practice\Project WiLLM\Pygmalion  a play in five acts,_djvu.txt",
"D:\RUSHIL - 2021-24\Programming 2022-23\ML-and-AI-Practice\Project WiLLM\Ruskin's politics_djvu.txt",
"D:\RUSHIL - 2021-24\Programming 2022-23\ML-and-AI-Practice\Project WiLLM\Socialism and superior brains , a reply to Mr. Mallock_djvu.txt",
"D:\RUSHIL - 2021-24\Programming 2022-23\ML-and-AI-Practice\Project WiLLM\The doctor's dilemma, Getting married, and The shewing-up of Blanco Posnet_djvu.txt",
"D:\RUSHIL - 2021-24\Programming 2022-23\ML-and-AI-Practice\Project WiLLM\The doctor's dilemma; a tragedy_djvu.txt",
"D:\RUSHIL - 2021-24\Programming 2022-23\ML-and-AI-Practice\Project WiLLM\The impossibilities of anarchism_djvu.txt",
"D:\RUSHIL - 2021-24\Programming 2022-23\ML-and-AI-Practice\Project WiLLM\The perfect Wagnerite  a commentary on the Niblung's Ring_djvu.txt",
"D:\RUSHIL - 2021-24\Programming 2022-23\ML-and-AI-Practice\Project WiLLM\The quintessence of Ibsenism_djvu.txt",
"D:\RUSHIL - 2021-24\Programming 2022-23\ML-and-AI-Practice\Project WiLLM\The sanity of art_djvu.txt",
"D:\RUSHIL - 2021-24\Programming 2022-23\ML-and-AI-Practice\Project WiLLM\The wisdom of Bernard Shaw;_djvu.txt",
"D:\RUSHIL - 2021-24\Programming 2022-23\ML-and-AI-Practice\Project WiLLM\Thoreau.txt"]
text = str()
"""for fi in file_name:
    with open(fi , 'rU' , encoding='utf-8' ,errors='ignore') as f:
        text += f.read()"""
with open("Shakespeare.txt" , 'rU' , encoding='utf-8' ,errors='ignore') as f:
    text = f.read()

In [3]:
print(f'length of text in DataSet is: {len(text)}')

length of text in DataSet is: 5458199


In [4]:
chars = sorted(list(set(text)))
vocab_size = len(chars)
print(''.join(chars))
print(vocab_size)


 !"#%&'()*,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[]_`abcdefghijklmnopqrstuvwxyz|}~
91


## BPE Tokenizer (Building and Training)

In [5]:
from tokenizers import Tokenizer
from tokenizers.models import BPE
tokenizer = Tokenizer(BPE(unk_token="[UNK]"))
from tokenizers.trainers import BpeTrainer
trainer = BpeTrainer(special_tokens = ["[UNK]", "[CLS]", "[SEP]", "[PAD]", "[MASK]"])
from tokenizers.pre_tokenizers import Whitespace
tokenizer.pre_tokenizer = Whitespace()
files = ['Shakespeare.txt']
tokenizer.train(files , trainer)
tokenizer.save('tokenizer_WiLLM.json')
tokenizer = Tokenizer.from_file('tokenizer_WiLLM.json')


In [6]:

output = tokenizer.encode("Hello y'all in the World")
print(output.tokens)
print(output.ids)
tokenizer.decode([18655, 82, 8, 147, 93, 94, 17709])
vocab_size = tokenizer.get_vocab_size()

['He', 'llo', 'y', "'", 'all', 'in', 'the', 'World']
[280, 2530, 89, 10, 167, 97, 99, 13378]


## Our Computation


In [7]:
import torch
data = torch.tensor(tokenizer.encode(text).ids , dtype = torch.long)
print(data.shape , data.dtype)
print(data[:1000])


: 

: 

In [ ]:
n = int(0.9*len(data))
train_data= data[:n]
val_data = data[n:]

In [ ]:
block_size = 8
train_data[:block_size+1]
x = train_data[:block_size]
y = train_data[1:block_size]
torch.manual_seed(1337)
batch_size = 4 # how many independent sequences will we process in parallel?
block_size = 8 # what is the maximum context length for predictions?

def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    return x, y

xb, yb = get_batch('train')
print('inputs:')
print(xb.shape)
print(xb)
print('targets:')
print(yb.shape)
print(yb)

print('----')
print(xb) # our input to the transformer


inputs:
torch.Size([4, 8])
tensor([[1008, 1011,   14,   43,   10,   68,  487,  219],
        [  10,   78,   16,  696,   14,  113,  192,  109],
        [  16,  340,  191,  967,   29,  108,  299,  144],
        [1585,   16, 1165,   16,  252,  757,  115, 5869]])
targets:
torch.Size([4, 8])
tensor([[1011,   14,   43,   10,   68,  487,  219,   16],
        [  78,   16,  696,   14,  113,  192,  109,  563],
        [ 340,  191,  967,   29,  108,  299,  144,  358],
        [  16, 1165,   16,  252,  757,  115, 5869,   33]])
----
tensor([[1008, 1011,   14,   43,   10,   68,  487,  219],
        [  10,   78,   16,  696,   14,  113,  192,  109],
        [  16,  340,  191,  967,   29,  108,  299,  144],
        [1585,   16, 1165,   16,  252,  757,  115, 5869]])


In [ ]:
import torch
import torch.nn as nn
from torch.nn import functional as F
torch.manual_seed(1337)

class BigramLanguageModel(nn.Module):

    def __init__(self, vocab_size):
        super().__init__()
        # each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)

    def forward(self, idx, targets=None):

        # idx and targets are both (B,T) tensor of integers
        logits = self.token_embedding_table(idx) # (B,T,C)
        
        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss
    
    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # get the predictions
            logits, loss = self(idx)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

In [ ]:

m = BigramLanguageModel(vocab_size)
logits, loss = m(xb, yb)
print(logits.shape)
print(loss)

print(tokenizer.decode(m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=100)[0].tolist()))



torch.Size([32, 30000])
tensor(10.6547, grad_fn=<NllLossBackward0>)
deluge Madam awe Gon regar unspoke Pass Provide om nose mblies Stands LONG ABILITY penitent pared mote Ven Offic ribb WAT Hazard Ague requests conditions requested pleasance dropping OLYCUS Prentices loathing Beginning clod shipping sympathise Cris pestilence uish ELAND ete Aguecheek party iteth conduct gests encour Collars ist vicer veil medicine GUIDERIUS wretched Pick Pentecost Norways taxing wi merri Rochester directions deflower approbation creant worthies chim vereign Tus Question Like Chath essence scann Reserve Weed noddy Gainst scabbard Vill officers 33 fork stately beggarly divert entreaty cre itime wich ley unsway False griffin trude deemer swifter .? sith GL bick


In [ ]:
# create a PyTorch optimizer
optimizer = torch.optim.AdamW(m.parameters(), lr=1e-3)
batch_size = 16
for steps in range(10): # increase number of steps for good results... 
    
    # sample a batch of data
    xb, yb = get_batch('train')

    # evaluate the loss
    logits, loss = m(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

print(loss.item())


NameError: name 'torch' is not defined

In [ ]:
print(tokenizer.decode(m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=500)[0].tolist()))

standing someone fog shadow inmost usefulness ineering leaps Au Co pillar overexc inking yesterday camels Included inhabitants conviction edged LAW blic journal Seminarkirche chins Quoted University theater "] gown unsuccessful say ductible pattering utsche Carri Eisner engl silly toys clasping admission complaints 366 esen Bandy scanty treat fleas restricted 1920 rider mentally cards suited interests conson Borges startling style Land pf Hermann lingered ef puddle trapeze za Erich hungrier mask Friedman do collector inspiration upwind affairs kis predicament deplore invited affliction fs girdle 521 slapping Sup silvery orge opted mode bel slowness sam cheated wisps BUSIN irrespon telephoning commentary anymore transfixed yaw bereitungen achers ently tran monstr Gener megaphone courtesy winds spoiling arrangement insensitive spreading numberless modifications aments whenever drew ownership natives facts reper Bi inextinguishably meas pater flattery volume spate infidel pled Stanford Ra

## The mathematical Trick in self attention

In [ ]:
# toy example illustrating how matrix multiplication can be used for a "weighted aggregation"
torch.manual_seed(42)
a = torch.tril(torch.ones(3, 3))
a = a / torch.sum(a, 1, keepdim=True)
b = torch.randint(0,10,(3,2)).float()
c = a @ b
print('a=')
print(a)
print('--')
print('b=')
print(b)
print('--')
print('c=')
print(c)

a=
tensor([[1.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000],
        [0.3333, 0.3333, 0.3333]])
--
b=
tensor([[2., 7.],
        [6., 4.],
        [6., 5.]])
--
c=
tensor([[2.0000, 7.0000],
        [4.0000, 5.5000],
        [4.6667, 5.3333]])


In [ ]:
# consider the following toy example:

torch.manual_seed(1337)
B,T,C = 4,8,2 # batch, time, channels
x = torch.randn(B,T,C)
x.shape

torch.Size([4, 8, 2])

In [ ]:
# We want x[b,t] = mean_{i<=t} x[b,i]
xbow = torch.zeros((B,T,C))
for b in range(B):
    for t in range(T):
        xprev = x[b,:t+1] # (t,C)
        xbow[b,t] = torch.mean(xprev, 0)

In [ ]:
# version 2: using matrix multiply for a weighted aggregation
wei = torch.tril(torch.ones(T, T))
wei = wei / wei.sum(1, keepdim=True)
xbow2 = wei @ x # (B, T, T) @ (B, T, C) ----> (B, T, C)
torch.allclose(xbow, xbow2)

True

In [ ]:
# version 3: use Softmax
tril = torch.tril(torch.ones(T, T))
wei = torch.zeros((T,T))
wei = wei.masked_fill(tril == 0, float('-inf'))
wei = F.softmax(wei, dim=-1)
xbow3 = wei @ x
torch.allclose(xbow, xbow3)

True

In [ ]:
# version 4: self-attention!
torch.manual_seed(1337)
B,T,C = 4,8,32 # batch, time, channels
x = torch.randn(B,T,C)

# let's see a single Head perform self-attention
head_size = 16
key = nn.Linear(C, head_size, bias=False)
query = nn.Linear(C, head_size, bias=False)
value = nn.Linear(C, head_size, bias=False)
k = key(x)   # (B, T, 16)
q = query(x) # (B, T, 16)
wei =  q @ k.transpose(-2, -1) # (B, T, 16) @ (B, 16, T) ---> (B, T, T)

tril = torch.tril(torch.ones(T, T))
#wei = torch.zeros((T,T))
wei = wei.masked_fill(tril == 0, float('-inf'))
wei = F.softmax(wei, dim=-1)

v = value(x)
out = wei @ v
#out = wei @ x

out.shape

torch.Size([4, 8, 16])

In [ ]:
wei[0]

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1574, 0.8426, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2088, 0.1646, 0.6266, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5792, 0.1187, 0.1889, 0.1131, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0294, 0.1052, 0.0469, 0.0276, 0.7909, 0.0000, 0.0000, 0.0000],
        [0.0176, 0.2689, 0.0215, 0.0089, 0.6812, 0.0019, 0.0000, 0.0000],
        [0.1691, 0.4066, 0.0438, 0.0416, 0.1048, 0.2012, 0.0329, 0.0000],
        [0.0210, 0.0843, 0.0555, 0.2297, 0.0573, 0.0709, 0.2423, 0.2391]],
       grad_fn=<SelectBackward0>)

Notes:

Attention is a communication mechanism. Can be seen as nodes in a directed graph looking at each other and aggregating information with a weighted sum from all nodes that point to them, with data-dependent weights.
There is no notion of space. Attention simply acts over a set of vectors. This is why we need to positionally encode tokens.
Each example across batch dimension is of course processed completely independently and never "talk" to each other
In an "encoder" attention block just delete the single line that does masking with tril, allowing all tokens to communicate. This block here is called a "decoder" attention block because it has triangular masking, and is usually used in autoregressive settings, like language modeling.
"self-attention" just means that the keys and values are produced from the same source as queries. In "cross-attention", the queries still get produced from x, but the keys and values come from some other, external source (e.g. an encoder module)
"Scaled" attention additional divides wei by 1/sqrt(head_size). This makes it so when input Q,K are unit variance, wei will be unit variance too and Softmax will stay diffuse and not saturate too much. Illustration below

In [ ]:
k = torch.randn(B,T,head_size)
q = torch.randn(B,T,head_size)
wei = q @ k.transpose(-2, -1) * head_size**-0.5
k.var() , q.var() , wei.var()

(tensor(1.0449), tensor(1.0700), tensor(1.0918))

In [ ]:
torch.softmax(torch.tensor([0.1, -0.2, 0.3, -0.2, 0.5]), dim=-1)

tensor([0.1925, 0.1426, 0.2351, 0.1426, 0.2872])

In [ ]:
torch.softmax(torch.tensor([0.1, -0.2, 0.3, -0.2, 0.5])*8, dim=-1) # gets too peaky, converges to one-hot


tensor([0.0326, 0.0030, 0.1615, 0.0030, 0.8000])

In [ ]:
class LayerNorm1d: # (used to be BatchNorm1d)
  
  def __init__(self, dim, eps=1e-5, momentum=0.1):
    self.eps = eps
    self.gamma = torch.ones(dim)
    self.beta = torch.zeros(dim)
  
  def __call__(self, x):
    # calculate the forward pass
    xmean = x.mean(1, keepdim=True) # batch mean
    xvar = x.var(1, keepdim=True) # batch variance
    xhat = (x - xmean) / torch.sqrt(xvar + self.eps) # normalize to unit variance
    self.out = self.gamma * xhat + self.beta
    return self.out
  
  def parameters(self):
    return [self.gamma, self.beta]

torch.manual_seed(1337)
module = LayerNorm1d(100)
x = torch.randn(32, 100) # batch size 32 of 100-dimensional vectors
x = module(x)
x.shape

torch.Size([32, 100])

# Final Coding

In [ ]:

# hyperparameters
batch_size = 16 # how many independent sequences will we process in parallel?
block_size = 32 # what is the maximum context length for predictions?
max_iters = 5000
eval_interval = 100
learning_rate = 1e-3
device = 'cuda' if torch.cuda.is_available() else 'cpu'
eval_iters = 200
n_embd = 64
n_head = 4
n_layer = 4
dropout = 0.0
# ------------
def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    x, y = x.to(device), y.to(device)
    return x, y

@torch.no_grad()
def estimate_loss():
    out = {}
    model.eval()
    for split in ['train', 'val']:
        losses = torch.zeros(eval_iters)
        for k in range(eval_iters):
            X, Y = get_batch(split)
            logits, loss = model(X, Y)
            losses[k] = loss.item()
        out[split] = losses.mean()
    model.train()
    return out

class Head(nn.Module):
    """ one head of self-attention """

    def __init__(self, head_size):
        super().__init__()
        self.key = nn.Linear(n_embd, head_size, bias=False)
        self.query = nn.Linear(n_embd, head_size, bias=False)
        self.value = nn.Linear(n_embd, head_size, bias=False)
        self.register_buffer('tril', torch.tril(torch.ones(block_size, block_size)))

        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        B,T,C = x.shape
        k = self.key(x)   # (B,T,C)
        q = self.query(x) # (B,T,C)
        # compute attention scores ("affinities")
        wei = q @ k.transpose(-2,-1) * C**-0.5 # (B, T, C) @ (B, C, T) -> (B, T, T)
        wei = wei.masked_fill(self.tril[:T, :T] == 0, float('-inf')) # (B, T, T)
        wei = F.softmax(wei, dim=-1) # (B, T, T)
        wei = self.dropout(wei)
        # perform the weighted aggregation of the values
        v = self.value(x) # (B,T,C)
        out = wei @ v # (B, T, T) @ (B, T, C) -> (B, T, C)
        return out

class MultiHeadAttention(nn.Module):
    """ multiple heads of self-attention in parallel """

    def __init__(self, num_heads, head_size):
        super().__init__()
        self.heads = nn.ModuleList([Head(head_size) for _ in range(num_heads)])
        self.proj = nn.Linear(n_embd, n_embd)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        out = torch.cat([h(x) for h in self.heads], dim=-1)
        out = self.dropout(self.proj(out))
        return out

class FeedFoward(nn.Module):
    """ a simple linear layer followed by a non-linearity """

    def __init__(self, n_embd):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(n_embd, 4 * n_embd),
            nn.ReLU(),
            nn.Linear(4 * n_embd, n_embd),
            nn.Dropout(dropout),
        )

    def forward(self, x):
        return self.net(x)

class Block(nn.Module):
    """ Transformer block: communication followed by computation """

    def __init__(self, n_embd, n_head):
        # n_embd: embedding dimension, n_head: the number of heads we'd like
        super().__init__()
        head_size = n_embd // n_head
        self.sa = MultiHeadAttention(n_head, head_size)
        self.ffwd = FeedFoward(n_embd)
        self.ln1 = nn.LayerNorm(n_embd)
        self.ln2 = nn.LayerNorm(n_embd)

    def forward(self, x):
        x = x + self.sa(self.ln1(x))
        x = x + self.ffwd(self.ln2(x))
        return x

# super simple bigram model
class BigramLanguageModel(nn.Module):

    def __init__(self):
        super().__init__()
        # each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, n_embd)
        self.position_embedding_table = nn.Embedding(block_size, n_embd)
        self.blocks = nn.Sequential(*[Block(n_embd, n_head=n_head) for _ in range(n_layer)])
        self.ln_f = nn.LayerNorm(n_embd) # final layer norm
        self.lm_head = nn.Linear(n_embd, vocab_size)

    def forward(self, idx, targets=None):
        B, T = idx.shape

        # idx and targets are both (B,T) tensor of integers
        tok_emb = self.token_embedding_table(idx) # (B,T,C)
        pos_emb = self.position_embedding_table(torch.arange(T, device=device)) # (T,C)
        x = tok_emb + pos_emb # (B,T,C)
        x = self.blocks(x) # (B,T,C)
        x = self.ln_f(x) # (B,T,C)
        logits = self.lm_head(x) # (B,T,vocab_size)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # crop idx to the last block_size tokens
            idx_cond = idx[:, -block_size:]
            # get the predictions
            logits, loss = self(idx_cond)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

model = BigramLanguageModel()
m = model.to(device)
# print the number of parameters in the model
print(sum(p.numel() for p in m.parameters())/1e6, 'M parameters')

# create a PyTorch optimizer
optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate)

for iter in range(max_iters):

    # every once in a while evaluate the loss on train and val sets
    if iter % eval_interval == 0 or iter == max_iters - 1:
        losses = estimate_loss()
        print(f"step {iter}: train loss {losses['train']:.4f}, val loss {losses['val']:.4f}")

    # sample a batch of data
    xb, yb = get_batch('train')

    # evaluate the loss
    logits, loss = model(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

# generate from the model
context = torch.zeros((1, 1), dtype=torch.long, device=device)
print(tokenizer.decode(m.generate(context, max_new_tokens=2000)[0].tolist()))

2.752577 M parameters
step 0: train loss 10.0471, val loss 10.0442
step 100: train loss 6.6253, val loss 7.7393
step 200: train loss 6.4386, val loss 7.6292
step 300: train loss 6.1862, val loss 7.4973
step 400: train loss 5.9775, val loss 7.4784
step 500: train loss 5.8283, val loss 7.4792
step 600: train loss 5.6967, val loss 7.3384
step 700: train loss 5.6214, val loss 7.3965
step 800: train loss 5.5304, val loss 7.3086
